name: Publish kool snapshot

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish snapshot
    runs-on: ubuntu-latest
    environment: publish-snapshot

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Enable Android target
        run: ./gradlew enableAndroidPlatform
      - name: Build everything
        run: ./gradlew build
      - name: Publish snapshot
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}